<a href="https://colab.research.google.com/github/tae-yeop/transformer-adventure/blob/main/einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.rand((2,3))

In [ ]:
# Permutation of Tensors
torch.einsum("ij->ji", x)

tensor([[0.0210, 0.3896],
        [0.6478, 0.4792],
        [0.2264, 0.1302]])

In [ ]:
# Summation
torch.einsum("ij->",x)

tensor(1.8942)

In [ ]:
# Column sum
torch.einsum("ij->j", x)

tensor([0.4105, 1.1270, 0.3567])

In [ ]:
# Row sum
torch.einsum("ij->i", x)

tensor([0.8952, 0.9990])

In [ ]:
# Mat-vector mul
v = torch.rand((1,3))
torch.einsum("ik, jk-> ij", x, v)  

tensor([[0.6803],
        [0.5428]])

In [ ]:
# Mat- MAt mul
x.mm(x.t())

tensor([[0.4713, 0.3481],
        [0.3481, 0.3984]])

In [ ]:
torch.einsum('ij,kj->ik', x,x) #2x2 = 2x3 x 3x2

tensor([[0.4713, 0.3481],
        [0.3481, 0.3984]])

In [ ]:
# dot product first row with first row of matrix
torch.einsum("i,i->", x[0], x[0])

tensor(0.4713)

In [ ]:
# dot product with matrix
torch.einsum("ij,ij->", x,x)

tensor(0.8697)

In [ ]:
# Hadarmard product (element-wise mul)
torch.einsum("ij,ij->ij",x,x)

tensor([[0.0004, 0.4196, 0.0513],
        [0.1518, 0.2297, 0.0170]])

In [ ]:
# Outer Product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum("i,j->ij", a, b)

tensor([[0.0173, 0.0168, 0.0109, 0.0098, 0.0115],
        [0.6634, 0.6455, 0.4171, 0.3767, 0.4407],
        [0.0181, 0.0176, 0.0114, 0.0103, 0.0120]])

In [ ]:
# Batch Mat Mul torch.bmm
a = torch.rand((3,2,5))
b = torch.rand((3,5,3))
torch.einsum("ijk, ikl->ijl", a,b)

tensor([[[1.2259, 1.6076, 1.2571],
         [0.6729, 0.8537, 0.6645]],

        [[1.1284, 0.6684, 1.5305],
         [0.8756, 0.3105, 1.1591]],

        [[0.6177, 1.1588, 1.6288],
         [0.4138, 1.6821, 1.6748]]])

In [ ]:
# matrix diagonal
x = torch.rand((3,3))
print(x)
print(torch.einsum("ii->i",x))

tensor([[0.9161, 0.7520, 0.3607],
        [0.4375, 0.4931, 0.9783],
        [0.3216, 0.2977, 0.7750]])
tensor([0.9161, 0.4931, 0.7750])


In [ ]:
# matrix trace
torch.einsum("ii->",x)

tensor(2.1842)